Find vulnerabilities sanity test
elastic/cloudbeat pull request #1110
Opened 2023-07-04 08:09 UTC by amirbenun

### Summary of your changes
Add sanity test for CNVM:
Iterate over `cloud_security_posture.vulnerabilities` index to make sure it is populated.

### Related Issues
- Resolves: https://github.com/elastic/cloudbeat/issues/700

### Checklist
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

2023-07-10 10:29 UTC, oren-zohar requested changes

2023-07-10 10:29 UTC, oren-zohar commented on tests/commonlib/io_utils.py
> -    index_name: str,
update docstring for removed parameter

2023-07-10 10:29 UTC, oren-zohar commented on tests/commonlib/utils.py
> +        time.sleep(5)
can you put it into a const with a meaningful name please?

2023-07-10 10:29 UTC, oren-zohar commented on tests/integration/tests/test_sanity_checks.py
> +def test_cnvm_findings(cnvm_client):
Just for consistency and clarity, I would keep it in the same format (which means we need to update `test_data` on line 15) but your call
```suggestion
@pytest.mark.sanity
@pytest.mark.parametrize("match_type", tests_data["cnvm"])
def test_cnvm_findings(cnvm_client):
```

2023-07-10 10:29 UTC, oren-zohar commented on tests/configuration.py
> +VULNERABILITIES_INDEX_PATTETRN = "*cloud_security_posture.vulnerabilities*"
```suggestion
FINDINGS_INDEX_PATTERN = "*cloud_security_posture.findings*"
VULNERABILITIES_INDEX_PATTERN = "*cloud_security_posture.vulnerabilities*"
```

2023-07-11 14:32 UTC, amirbenun commented
Working workflow:
https://github.com/amirbenun/cloudbeat/actions/runs/5520102753/jobs/10066260670

2023-07-11 14:36 UTC, oren-zohar approved these changes

2023-07-11 14:52 UTC, merged