Adding capability of running automated process rules tests
elastic/cloudbeat pull request #127
Opened 2022-05-11 15:01 UTC by jeniawhite

Enhancing the tests framework to automatically evaluate process rules

Fixes https://github.com/elastic/cloudbeat/issues/157

2022-05-12 05:53 UTC, gurevichdmitry requested changes
Please create a separate file for process rule tests and check if it possible to move sleep method to test level

2022-05-12 05:53 UTC, gurevichdmitry commented on tests/commonlib/io_utils.py
> +        time.sleep(60)
Not a good idea to put sleep function on infra level.

2022-05-12 05:53 UTC, gurevichdmitry commented on tests/product/tests/test_rules.py
> +def test_process_rules(data,
It is possible to create a separate file for process rule tests.

2022-05-24 08:08 UTC, gurevichdmitry approved these changes
LGTM

2022-05-26 09:08 UTC, DaveSys911 approved these changes
LGTM

2022-05-26 12:18 UTC, uri-weisman requested changes
GJ Jenia!! 💪 
Added few comments...

2022-05-26 12:18 UTC, uri-weisman commented on tests/commonlib/io_utils.py
> +    @staticmethod
Can we plz add some description to the function?

2022-05-26 12:18 UTC, uri-weisman commented on tests/commonlib/io_utils.py
> +        for skey, svalue in set_dict.items():
Not very easy to understand from the first glimpse, an explanation or even simplifying code will be great.

2022-05-26 12:18 UTC, uri-weisman commented on tests/product/tests/test_process_api_server_rules.py
> +"""
Is there a reason to create a test file for each process, from first sight logic looks quite similar?

2022-05-26 14:54 UTC, uri-weisman approved these changes

2022-05-26 14:57 UTC, merged