Add bump-beats pipeline
elastic/cloudbeat pull request #1494
Opened 2023-10-27 11:41 UTC by orestisfl

### Summary of your changes
Mostly copied from apm-server.

I have no access to vault secrets so I don't know how to test this for now.

### Checklist
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

2023-10-30 08:40 UTC, oren-zohar requested changes
@orestisfl ~~did you test it?~~ oh nvm I saw your comment about the vault secrets right now, let's sync offline

2023-10-30 09:01 UTC, orestisfl commented on .pre-commit-config.yaml
> +        files: (deploy/azure/.*sh|scripts/publish_cft.sh|.ci/scripts/update-beats.sh)
These are the files that the pipeline actually runs on, not the ones that are excluded.

2023-10-30 09:02 UTC, orestisfl commented on .github/workflows/update-beats.yml
> +          BRANCH_NAME: ${{ matrix.branch }}
Probably to update dependencies for older versions as well, but perhaps it's less important for us and we can skip the extra complexity and only run it on main?

2023-10-30 14:19 UTC, orestisfl commented on .github/workflows/update-beats.yml
> +        uses: elastic/apm-pipeline-library/.github/actions/elastic-stack-snapshot-branches@current
@gurevichdmitry The bump-golang job does use vault secrets: https://github.com/elastic/cloudbeat/actions/runs/6693205116/job/18183872641

2023-10-31 09:11 UTC, oren-zohar approved these changes

2023-11-02 11:01 UTC, merged

2023-11-02 12:47 UTC, v1v commented
> I have no access to vault secrets so I don't know how to test this for now.


You can test it locally by overriding the variables:

```
JOB_URL=noop \
    GIT_USER=noop \
    GIT_EMAIL=noop \
    GITHUB_TOKEN=your-token \
     updatecli apply --config .ci/bump-beats.yml --push=false --debug
```

2023-11-02 14:51 UTC, orestisfl commented
> You can test it locally by overriding the variables:

I did, but I don't think it's possible to test the GH (not updatecli) action without access.