Create custom user package to obtain host user data
elastic/cloudbeat pull request #152
Opened 2022-05-16 14:18 UTC by uri-weisman

2022-05-16 15:09 UTC, uri-weisman commented
fixes #118

2022-05-17 07:58 UTC, uri-weisman commented on resources/utils/user.go
> +	if usr.Name != "" {
In case the user was not created with a friendly comment, `useradd -c "etcd"`, we'll return the username.

2022-05-17 09:03 UTC, uri-weisman commented on resources/utils/user.go
> +	if usr.Name != "" {
e.g `list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin`
if "Mailing List Manager" doesn't exists use `list`

2022-05-17 15:49 UTC, eyalkraft requested changes
Nice tests! small changes required

2022-05-17 15:49 UTC, eyalkraft commented on resources/utils/mocked_group_file.txt
> +wheel:*:0:root
nice, let's move both mocks into `resources/utils/mock/`

2022-05-18 09:25 UTC, uri-weisman commented on resources/fetchers/file_system_fetcher.go
> +		Uid:      utils.GetUserNameFromID(uid, UserFile),
https://github.com/elastic/security-team/issues/3889

2022-05-22 12:15 UTC, eyalkraft approved these changes
Test and ship

2022-05-22 12:28 UTC, merged