Adding metadata to EKS
elastic/cloudbeat pull request #164
Opened 2022-05-21 12:29 UTC by ofiriro3

- Fixes: https://github.com/elastic/security-team/issues/3931

2022-05-22 08:01 UTC, uri-weisman requested changes

2022-05-23 09:12 UTC, ofiriro3 commented on resources/fetchers/ecr_fetcher.go
> +	"github.com/google/uuid"
Done

2022-05-23 09:24 UTC, ofiriro3 commented on resources/fetchers/ecr_fetcher.go
> +		Name:    "AWS repositories",
Very similar answer to the above.

What name should it have?

2022-05-23 09:35 UTC, uri-weisman commented on resources/fetchers/iam_fetcher.go
> +	IAMRolePermissionsResponse
👍

2022-05-23 09:39 UTC, uri-weisman commented on resources/fetchers/ecr_fetcher.go
> +		ID:      uid.String(),
It seems that we need to discuss it a bit more.
In order for it to work, it will be sufficient for now and later on we'll define it better.

2022-06-01 11:41 UTC, merged