Skip fleet API calls on integration tests
elastic/cloudbeat pull request #1866
Opened 2024-01-28 10:55 UTC by amirbenun

### Summary of your changes
The `test_sanity_checks` is called on both flows:
1. Integration tests
2. Sanity tests

On the integration tests, fleet and kibana are not up and therefore we can't use their API.
This fix skip calling fleet API when the `KIBANA_URL` environment variable is missing.

### Screenshot/Data

### Related Issues

### Checklist
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

#### Introducing a new rule?

- [ ] Generate rule metadata using [this script](https://github.com/elastic/cloudbeat/tree/main/security-policies/dev#generate-rules-metadata)
- [ ] Add relevant unit tests
- [ ] Generate relevant rule templates using [this script](https://github.com/elastic/cloudbeat/tree/main/security-policies/dev#generate-rule-templates), and open a PR in [elastic/packages/cloud_security_posture](https://github.com/elastic/integrations/tree/main/packages/cloud_security_posture)

2024-01-28 12:21 UTC, oren-zohar requested changes

2024-01-28 12:21 UTC, oren-zohar commented on tests/commonlib/agents_map.py
> +        logger.info("amiramir loading map")
Please remove

2024-01-28 12:21 UTC, oren-zohar commented on tests/integration/tests/test_sanity_checks.py
> +        logger.info("amiramir skip loading map")
Please remove

2024-01-28 16:18 UTC, amirbenun commented
A successfull run: https://github.com/elastic/cloudbeat/actions/runs/7686877924

2024-01-29 08:33 UTC, gurevichdmitry commented on tests/conftest.py
>      return mapping
can be replaced by:

`return AgentComponentMapping()`

2024-01-29 08:38 UTC, gurevichdmitry reviewed
@amirbenun The successful run is only for sanity checks. Could you please execute the original workflow to ensure that this fixes both integrations and sanity checks together?

btw, another option to fix that is to execute only integration tests by eliminating sanity checks using a regular expression pattern.
`poetry run pytest -k "azure and not cspm_azure" --alluredir=./allure/results/ --clean-alluredir`

2024-01-29 09:12 UTC, oren-zohar approved these changes

2024-01-29 09:14 UTC, amirbenun commented
Another successful run: https://github.com/elastic/cloudbeat/actions/runs/7693498240/job/20962379730

2024-01-29 09:14 UTC, merged