change azure-ci to run postmerge
elastic/cloudbeat pull request #1868
Opened 2024-01-28 16:20 UTC by orouz

running this workflow on `pull_request_target` means that PRs that introduce new azure integration tests won't run until they are merged, which could lead to CI failing in PRs with unrelated, previously introduced tests. 

this PR changes the workflow to run post-merge, which makes it so that every new azure test that is added is checked once it's merged

2024-01-29 08:25 UTC, gurevichdmitry commented on .github/workflows/azure-ci.yml
>      inputs:
@orouz, I believe the workflow_dispatch was initially used to test the Azure-CI workflow, and now that the workflow is functioning correctly, can we remove this trigger as well?

2024-01-30 11:50 UTC, orestisfl approved these changes

2024-01-31 08:17 UTC, oren-zohar requested changes
It should be both post and pre merge, no?

2024-02-04 14:03 UTC, oren-zohar approved these changes

2024-02-04 14:47 UTC, merged