Update csp-security-policies to v1.1.0
elastic/cloudbeat pull request #387
Opened 2022-09-13 10:39 UTC by yashtewari

Includes major refactors to the new audit design.

2022-09-13 12:36 UTC, eyalkraft approved these changes

2022-09-15 12:30 UTC, DaveSys911 approved these changes
Works as a quick fix.

2022-09-18 19:30 UTC, oren-zohar requested changes
please include https://github.com/elastic/csp-security-policies/commit/67be1dcd34628b48286d5a7aef76c8da22cec87d in this PR

2022-09-18 19:31 UTC, oren-zohar requested changes

2022-09-18 19:31 UTC, oren-zohar commented on tests/commonlib/utils.py
> +
left on purpose?

2022-09-18 19:31 UTC, oren-zohar commented on tests/commonlib/utils.py
> +                print('FINDING MATCH:', event)
left on purpose?

2022-10-02 08:29 UTC, closed without merging