Delegate opa logger to logp lib
elastic/cloudbeat pull request #390
Opened 2022-09-13 18:55 UTC by amirbenun

2022-09-14 06:09 UTC, oren-zohar requested changes
Looks good, need to generate license headers with `mage addLicenseHeaders`. Did you test it? can you please share how the logs look now?

2022-09-14 06:09 UTC, oren-zohar commented on evaluator/logger.go
> +	ret := []interface{}{}
```suggestion
	var ret []interface{}
```
as a rule of thumb, we should try to use nil slice declaration wherever we can so an empty result will be comparable with nill, see an [exmaple](https://go.dev/play/p/V8pesYrwZBY)

2022-09-14 06:09 UTC, oren-zohar commented on evaluator/logger.go
> +	return logging.Level(4)
what does 4 stand for? level.Debug is 3

2022-09-20 15:55 UTC, amirbenun commented
Fleet UI logs screenshot:
![image](https://user-images.githubusercontent.com/34831306/191306316-85c668ba-bfa9-4927-8a01-217982b1781d.png)

Note that "Bundle load failed..." is produced by OPA.

2022-09-20 23:48 UTC, oren-zohar approved these changes
🚀 🚀 🚀 🚀

2022-09-21 08:29 UTC, merged