Removed redudent ops code
elastic/cloudbeat pull request #408
Opened 2022-09-21 02:11 UTC by DaveSys911

Signed-off-by: David Natachanny <David.Natachanny@elastic.co>

2022-09-21 21:54 UTC, DaveSys911 commented
@oren-zohar Ready for review.

2022-09-22 07:22 UTC, oren-zohar commented
@DaveSys911 how can I test it? what will it affect?

2022-09-22 20:17 UTC, DaveSys911 commented
> @DaveSys911 how can I test it? what will it affect? 

Already tested.
Jenkins pipeline & cloudbeat-ci build & pre-merge should path.

2022-10-02 09:22 UTC, oren-zohar requested changes
please remove the autopep8

2022-10-02 09:22 UTC, oren-zohar commented on scripts/make/generate_notice.py
>  DEFAULT_BUILD_TAGS = "darwin,linux,windows"
please revert changes here

2022-10-02 09:22 UTC, oren-zohar commented on scripts/make/generate_notice.py
> +            "go", "run", "-modfile=go.mod", "go.elastic.co/go-licence-detector",
except this chage

2022-10-02 10:38 UTC, DaveSys911 commented on scripts/make/generate_notice.py
>  DEFAULT_BUILD_TAGS = "darwin,linux,windows"
Done

2022-10-02 10:39 UTC, DaveSys911 commented
@oren-zohar added autopep conf file and set the "line too long" to ignore, so it won't run & flake8 will ignore it as well.

2022-10-02 11:37 UTC, oren-zohar approved these changes

2022-10-02 11:37 UTC, merged