Increase test timeout to mend CI.
elastic/cloudbeat pull request #415
Opened 2022-09-22 09:04 UTC by yashtewari

Workaround until we figure out why some findings are taking a long time to show up in the ES index after [this change](https://github.com/elastic/cloudbeat/commit/3c17c16c80c4ab6b78efa6bfaed8e9ec90fcecb2).

2022-09-22 11:05 UTC, oren-zohar commented
@yashtewari I think we can backport this change

2022-09-28 11:39 UTC, oren-zohar commented
@yashtewari let's backport it to 8.5.0

2022-09-28 13:03 UTC, oren-zohar requested changes

2022-09-28 13:03 UTC, oren-zohar commented on tests/product/tests/test_process_kubelet_rules.py
> +        # leading to unexpected findings structure.
please open a ticket for it and link it

2022-09-29 05:53 UTC, gurevichdmitry approved these changes
@yashtewari great job, approved.
Please update refactor task to fix all functions doc strings.

2022-09-29 06:13 UTC, oren-zohar approved these changes
🥇

2022-09-29 06:13 UTC, merged