Update Coverage badge flow
elastic/cloudbeat pull request #43
Opened 2022-04-12 13:49 UTC by oren-zohar

Update Coverage badge flow using coveralls.io, see an example for my fork [here](https://coveralls.io/github/oren-zohar/cloudbeat)

coveralls.io provides free service for tracking coverage for open source repos:
- coverage badge
- repo coverage graph over time
- setting coverage decline limit for PRs
___

- closes: https://github.com/elastic/security-team/issues/3496

2022-04-14 13:08 UTC, DaveSys911 commented
looks good, but as As discussed:
1. Move the unit test back to cloud beat-ci, right now unit tests are running on main branch instead of the pr, effectively removing it as a quality gate for the pr.
2. Add an additional workflow to be run post merge "on push to main" to run unit tests and update the badge.

It isn't possible to achieve both from one workflow.

2022-04-14 13:09 UTC, DaveSys911 requested changes
i see the badge is corrected, but as as discussed:
1. Move the unit test back to cloud beat-ci, right now unit tests are running on main branch instead of the pr, effectively removing it as a quality gate for the pr, since u removed the pr checkout.

3. Add an additional workflow to be run post merge "on push to main" to run unit tests and update the badge representing status of coverage on main, and not the pr branch.

It isn't possible to achieve both from one workflow.

2022-04-17 11:50 UTC, oren-zohar commented
> 1. Move the unit test back to cloud beat-ci, right now unit tests are running on main branch instead of the pr, effectively removing it as a quality gate for the pr, since u removed the pr checkout.

I'm not sure I'm following, I just split the same workflow into two separate ones with the same triggers. There is no reason to keep them together since they are logically separate, share no cache, and the yml is getting too large. 

> 2. Add an additional workflow to be run post merge "on push to main" to run unit tests and update the badge representing status of coverage on main, and not the pr branch.

the readme will always show the badge for main, not for the PR branch. Why do we need post-merge job?

2022-04-17 13:33 UTC, DaveSys911 approved these changes
Approved

2022-04-17 13:53 UTC, merged