Add just build-replace-cloudbeat command
elastic/cloudbeat pull request #448
Opened 2022-10-06 09:29 UTC by amirbenun

Add `just build-replace-cloudbeat` command that builds a cloudbeat binary and replaces it with the existing cloudbeat on your elastic-agent.

2022-10-06 13:12 UTC, oren-zohar requested changes
pleas add some documentation for the script functions and how to use it

2022-10-06 16:28 UTC, DaveSys911 approved these changes
LGTM for just file

2022-10-12 13:44 UTC, ofiriro3 commented
Amazing idea!

2022-10-18 08:28 UTC, amirbenun commented on scripts/common.sh
> +# The function returns the file name
I have added a bit more explanation, but I don't think an example should help here.
I don't expect users to use this function directly, it's more of a library function being used by other public functions.

2022-10-18 13:33 UTC, oren-zohar approved these changes

2022-10-18 13:44 UTC, merged