Fix cloudbeat's testing configuration - adding runtime_cfg to default config
elastic/cloudbeat pull request #472
Opened 2022-10-26 18:10 UTC by kfirpeled

Until now, without passing the proper configuration, `cloudbeat` evaluated resources against all the available benchmarks. This PR fix that behaviour to better mimic how things are working on production

2022-10-31 12:04 UTC, oren-zohar approved these changes

2022-10-31 12:16 UTC, oren-zohar commented
@kfirpeled maybe we should also edit [cloudbeat-pytest.yml](https://github.com/elastic/cloudbeat/blob/main/tests/deploy/cloudbeat-pytest.yml) and [cloudbeat-eks-pytest.yaml](https://github.com/elastic/cloudbeat/blob/main/tests/deploy/cloudbeat-eks-pytest.yaml). Not sure why we don't use the deployment ymls you edited in our functional tests infra, @gurevichdmitry @DaveSys911 maybe you can help here

2022-10-31 12:16 UTC, oren-zohar requested changes
@kfirpeled maybe we should also edit [cloudbeat-pytest.yml](https://github.com/elastic/cloudbeat/blob/main/tests/deploy/cloudbeat-pytest.yml) and [cloudbeat-eks-pytest.yaml](https://github.com/elastic/cloudbeat/blob/main/tests/deploy/cloudbeat-eks-pytest.yaml). Not sure why we don't use the deployment ymls you edited in our functional tests infra, @gurevichdmitry @DaveSys911 maybe you can help here

2022-11-07 10:26 UTC, gurevichdmitry commented
> @kfirpeled maybe we should also edit [cloudbeat-pytest.yml](https://github.com/elastic/cloudbeat/blob/main/tests/deploy/cloudbeat-pytest.yml) and [cloudbeat-eks-pytest.yaml](https://github.com/elastic/cloudbeat/blob/main/tests/deploy/cloudbeat-eks-pytest.yaml). Not sure why we don't use the deployment ymls you edited in our functional tests infra, @gurevichdmitry @DaveSys911 maybe you can help here

@oren-zohar, @kfirpeled , you are right, **cloudbeat-pytest.yml** and **cloudbeat-eks-pytest.yaml** should be updated appropriately.

2022-11-08 16:07 UTC, kfirpeled commented
I hope I've fixed everything, I've tested the template files using https://gotemplate.io/

@gurevichdmitry I've noticed that the period is set to 5s when testing eks. Are we sure that's ok? I remember it caused issues when doing the functional tests. Checkout: `tests/deploy/cloudbeat-eks-pytest.yaml:180`

2022-11-08 17:19 UTC, gurevichdmitry commented
> @gurevichdmitry I've noticed that the period is set to 5s when testing eks. Are we sure that's ok? I remember it caused issues when doing the functional tests. Checkout: `tests/deploy/cloudbeat-eks-pytest.yaml:180`

The period already changed in EKS functional tests PR.

2022-11-08 17:24 UTC, gurevichdmitry approved these changes
@kfirpeled, tests/deploy folder approved.

2022-11-09 12:57 UTC, oren-zohar requested changes

2022-11-10 15:39 UTC, oren-zohar approved these changes

2022-11-10 15:39 UTC, oren-zohar commented on README.md
> +The default `POLICY_TYPE` is set to `cloudbeat/cis_k8s` on `_meta/config/cloudbeat.common.yml.tmpl`
```suggestion
The default `POLICY_TYPE` is set to `cloudbeat/cis_k8s` on [`cloudbeat.common.yml.tmpl`](https://github.com/elastic/cloudbeat/blob/main/_meta/config/cloudbeat.common.yml.tmpl)
```

2022-11-10 16:58 UTC, merged