Refactor automated tests.
elastic/cloudbeat pull request #480
Opened 2022-11-02 11:20 UTC by yashtewari

2022-11-03 12:28 UTC, oren-zohar requested changes
Could you please summarize the checks we are going to ignore and the reasoning behind each one?

2022-11-07 08:48 UTC, yashtewari commented
> Could you please summarize the checks we are going to ignore and the reasoning behind each one?

@oren-zohar I've added the explanations within the code itself, and put the pytlinrc changes in a separate commit so it can be reviewed easily.

2022-11-10 15:58 UTC, oren-zohar requested changes
many line breaks need a fix, please ping me when this is ready for a review

2022-11-10 15:58 UTC, oren-zohar commented on tests/commonlib/io_utils.py
> +) -> list[Munch]:
please fix line breaks

2022-11-14 09:51 UTC, oren-zohar requested changes
I suggest using [black](https://github.com/psf/black) formatter to handle the line breaks automatically, or [yapf](https://github.com/google/yapf) (see `split_arguments_when_comma_terminated`)

2022-11-16 09:29 UTC, yashtewari commented on scripts/git-hooks/pre-commit
> +echo ""
To add a newline between the two reports.

2022-11-16 09:30 UTC, yashtewari commented on scripts/linter_setup.sh
> +#!/usr/bin/env bash
The shebang?

2022-11-16 10:47 UTC, yashtewari commented on scripts/git-hooks/pre-commit
> +flake8 --ignore="W503,W504,E203,E501" tests --include "tests/" --exclude "tests/venv"
Have moved flake8 configuration to `setup.cfg` and added comments explaining the need to ignore stuff.

2022-11-16 10:52 UTC, yashtewari commented
> I suggest using [black](https://github.com/psf/black) 

This is a great option; I especially like that it leaves no scope for any debate on style by enforcing its own style that can't be changed across projects. I've added it to the pre-commit checks. Unfortunately, it doesn't agree with our one-per-line function parameters from before, so it may be time to let go of them.

2022-11-25 15:21 UTC, yashtewari commented
Switched to using the [pre-commit](https://pre-commit.com) package. Fixed the multi-line parameter request.

2022-12-07 08:56 UTC, oren-zohar approved these changes

2022-12-07 08:56 UTC, merged