Resolve panic on race between data and beater
elastic/cloudbeat pull request #564
Opened 2022-12-04 09:21 UTC by jeniawhite

**What does this PR do?**
Due to the reconfiguration loop, I saw that `cloudbeat` panics sporadically.
While investigating the code, I noticed a race condition between the initialization of the wait group pointer to the closure of the `data` layer.
There is also a race for the publisher client that I've found, which will be covered later on.

**Checklist**
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

2022-12-04 09:38 UTC, amirbenun approved these changes

2022-12-04 09:44 UTC, oren-zohar requested changes
can we add test that fails with the previous struct? (closing before calling fetch)

2022-12-04 09:45 UTC, oren-zohar requested changes

2022-12-04 09:45 UTC, oren-zohar commented on resources/fetchersManager/data.go
> +	wg       sync.WaitGroup
can you please also add documentation for this wait group purpose?

2022-12-05 11:13 UTC, oren-zohar approved these changes

2022-12-05 14:19 UTC, merged