docs: update terraform
elastic/cloudbeat pull request #576
Opened 2022-12-12 09:24 UTC by olegsu

**What does this PR do?**
Update terraform doc with more examples

2022-12-12 09:31 UTC, eyalkraft approved these changes

2022-12-14 10:28 UTC, gurevichdmitry requested changes
@olegsu, LGTM. Please fix some typo issues.

2022-12-14 10:28 UTC, gurevichdmitry commented on deploy/cloud/README.md
>  ## Spesific version
```suggestion
## Specific version
```

2022-12-14 10:28 UTC, gurevichdmitry commented on deploy/cloud/README.md
>  To create an environment with spesific version use `terraform apply --auto-approve -var="stack_version=8.5.1"`
```suggestion
To create an environment with specific version use 

`terraform apply --auto-approve -var="stack_version=8.5.1"`
```

2022-12-14 10:28 UTC, gurevichdmitry commented on deploy/cloud/README.md
> +For example, to deploy `8.6.0-SNAPSHOT` use `terraform apply --auto-approve -var="stack_version=8.6.0-SNAPSHOT" -var="ess_region=gcp-us-west2"`
```suggestion
For example, to deploy `8.6.0-SNAPSHOT` use 

`terraform apply --auto-approve -var="stack_version=8.6.0-SNAPSHOT" -var="ess_region=gcp-us-west2"`
```

2022-12-14 10:28 UTC, gurevichdmitry commented on deploy/cloud/README.md
>  To give your environment a different prefix in the name use `terraform apply --auto-approve -var="deployment_name_prefix=elastic-deployment"`
```suggestion
To give your environment a different prefix in the name use 

`terraform apply --auto-approve -var="deployment_name_prefix=elastic-deployment"`
```

2022-12-14 12:46 UTC, gurevichdmitry approved these changes
LGTM

2022-12-14 12:46 UTC, merged