Fix OPA package build
elastic/cloudbeat pull request #594
Opened 2022-12-21 12:52 UTC by uri-weisman

**What does this PR do?**

Change the way we build OPA's bundle.
Before the change, we used the existing csp-security-policies go mod dependency (didn't require fetching the repo) - it was a dirty hack and we don't hold a `go.mod` in the policies repo anymore.

The new solution clones the csp-security-policies, find the latest tag which is not pre-release, and build the OPA bundle.

**Related Issues**
- https://github.com/elastic/csp-security-policies/pull/151

**Checklist**
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

2022-12-21 12:59 UTC, eyalkraft commented
How can we easily know with what version (commit/tag) of the policies repo is a specific cloudbeat commit built?
How can we control it?

(yet another reason to merge the repos :P)

2022-12-21 13:20 UTC, uri-weisman commented
> How can we easily know with what version (commit/tag) of the policies repo is a specific cloudbeat commit built? How can we control it?
> 
> (yet another reason to merge the repos :P)

Definitely another reason to merge.
I'm logging the commit + tag that is used for the bundle build.
Currently, we don't have any control over it, I can provide a `tag` param to the `BuildOpaBundle` function in case we want to override the release.

2022-12-21 13:34 UTC, oren-zohar requested changes
Fetching the latest release is a breaking change. We need to discuss the right strategy before doing so (adding automation for it + branching strategy in csp-rego-policies repo) so it's still too early for this change. Thanks for the initiative, either way, we will probably use this PR as ref in the future. Let's keep the previous behavior which was fetching a specific release version, we can set this version in `version/policy.go`

2022-12-21 14:02 UTC, oren-zohar requested changes
Thanks :pray: small comments

2022-12-21 14:02 UTC, oren-zohar commented on magefile.go
> +	log.Printf("Latest production release commit hash:", ref.Hash())
missing a placeholder

2022-12-21 14:02 UTC, oren-zohar commented on magefile.go
> +	sh.Run("bin/opa", "build", "-b", cspPoliciesPkgDir+"/bundle", "-e", cspPoliciesPkgDir+"/bundle/compliance")
error handling could be useful here

2022-12-21 15:42 UTC, merged

2022-12-25 10:09 UTC, amirbenun commented
This PR actually goes against our decision on [Define new release process for csp-security-policies](https://github.com/elastic/security-team/issues/2979).
Once a PR is merged to csp-security-policies repository it will be much easier to upgrade the dependency in cloudbeat using a `go get` command (as it used to be before that PR).
Can someone share more information about the reasoning behind that change?

2022-12-25 10:13 UTC, oren-zohar commented
> This PR actually goes against our decision on https://github.com/elastic/security-team/issues/2979.

How does it go against it?

> Once a PR is merged to csp-security-policies repository it will be much easier to upgrade the dependency in cloudbeat using a go get command (as it used to be before that PR).

https://github.com/elastic/csp-security-policies is no longer a go package (since we removed all go files and go.mod)

2022-12-25 10:17 UTC, amirbenun commented
I wasn't realized we removed the go files, makes more sense then.
And it goes against our decision because the dependency PRs to cloudbeat will be easier to automate with a `go get` command instead of changing a specific line of a specific file.

2022-12-25 12:38 UTC, uri-weisman commented
> I wasn't realized we removed the go files, makes more sense then. And it goes against our decision because the dependency PRs to cloudbeat will be easier to automate with a `go get` command instead of changing a specific line of a specific file.

As @oren-zohar mentioned, the CSP-policies can't be a go package anymore so this PR was a quick fix.
The following [code](https://github.com/elastic/cloudbeat/pull/594/commits/22a648e1571800289da376a57a64a87568886428#diff-520109d035a196d29d0a86e9c4e6c98e98abf056141b84df68c0d48167b87b25R381-L409) can help us with automating this process in the future, it basically retrieves the commit hash of the latest prod release.