Addition of non cert option
elastic/cloudbeat pull request #643
Opened 2023-01-03 16:30 UTC by jeniawhite

**What does this PR do?**
Adding an option to run `cloudbeat` without certificate

**Checklist**
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

2023-01-03 16:48 UTC, oren-zohar requested changes
Generally speaking, I think we should avoid adding more commands if we can instead add a parameter to the relevant commands. Additinionly, we also want to avoid adding more deployment config files, is it possible to edit the original kustomization file to toggle the cert part? @olegsu?

2023-01-03 16:48 UTC, oren-zohar commented on README.md
> +> ```
can you remove the part about `<Target OS>` and `GOOS` from the docs? it's no longer relevant

2023-01-04 08:21 UTC, olegsu commented
> is it possible to edit the original kustomization file to toggle the cert part? @olegsu?
Our options are
1. Use `kustomize` cli to update the kustomization file. For example `kustomize edit set image monopole/hello:1=monopole/hello:latest` will update the image. In this case, we need to check that we don't commit the changes.
2. Use kustomize [components](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md). This will require commenting out the component that we want to opt-out.
3. Use what @jeniawhite proposed. In that case, I think it would be better to also update [this](https://github.com/elastic/cloudbeat/blob/main/deploy/kustomize/overlays/cloudbeat-vanilla/kustomization.yml#L7) base to use the files from this pr.

2023-01-24 09:20 UTC, olegsu approved these changes

2023-01-24 10:08 UTC, oren-zohar commented on dev-docs/Development.md
> +Some tests use the new [expecter](<(https://github.com/vektra/mockery#expecter-interfaces)>) interface the library provides.
I think this change breaks the link

2023-01-29 09:38 UTC, JordanSh approved these changes
Worked like a charm 👍

2023-02-01 09:01 UTC, oren-zohar approved these changes

2023-02-01 09:29 UTC, merged