Collect account details for CIS AWS events
elastic/cloudbeat pull request #677
Opened 2023-01-26 15:12 UTC by ari-aviran

### Summary of your changes
Collect the following fields for CIS AWS findings:
- `cloud.account.name`
- `cloud.account.id`
- `cloud.provider`

In addition, refactor to the common data provider code to support multiple benchmarks with different types of common data gathered.

### Screenshot/Data
<img width="1840" alt="Screenshot 2023-01-29 at 10 54 03" src="https://user-images.githubusercontent.com/94899776/215315785-aedea60c-8c9d-4d6b-92c9-4f3aa49983fb.png">

### Related Issues
Resolves https://github.com/elastic/cloudbeat/issues/650
Resolves https://github.com/elastic/cloudbeat/issues/586

### Checklist
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

2023-01-26 15:16 UTC, ari-aviran commented on dataprovider/k8s_data_provider_test.go
> +func Test_k8sDataProvider_CollectK8sData(t *testing.T) {
Should be called `_GetData`

2023-01-29 10:29 UTC, uri-weisman requested changes
Really loved the new design! minor comments...

2023-01-29 10:29 UTC, uri-weisman commented on dataprovider/k8s_data_provider.go
>  	}
If we return an error in `NewK8sDataProvider` this logic can be removed.

2023-01-29 10:29 UTC, uri-weisman commented on resources/providers/awslib/iam/account_alias.go
> +func (p Provider) GetAccountAlias(ctx context.Context) (string, error) {
Can u please add a test for that?

2023-01-29 11:53 UTC, uri-weisman approved these changes

2023-01-29 11:53 UTC, uri-weisman commented on dataprovider/common_data_provider.go
> +	case "cis_eks", "cis_k8s":
nice

2023-01-29 11:53 UTC, merged