Addition of common data layer to transform
elastic/cloudbeat pull request #68
Opened 2022-04-27 16:09 UTC by jeniawhite

The purpose of this layer is to collect common constant data about the system that will be used to populate/enhance the fetcher's results.

The layer populates its data upon the creation of the cloud beat instance prior to running all of the fetchers logic.

In the first drop, we are populating the cluster_id and node_id that will be used in order to build the resource_ids for the fetched resources.

Currently, this layer only supports the collection of data running on top of K8S (aligned to other data collection across cloud beats).

There is the first step and this collection layer might get moved closer to the fetcher's level.

Fixes https://github.com/elastic/security-team/issues/3532

2022-04-27 18:46 UTC, uri-weisman requested changes
Good job Jenia 💪
I've added some minor comments.
BTW You probably need to modify the Transformer unit tests as well.

2022-04-27 18:46 UTC, uri-weisman commented on transformer/common_data.go
> +	hName, err := ioutil.ReadFile("/etc/hostname")
Plz store file path as a const.

2022-04-27 18:46 UTC, uri-weisman commented on transformer/events_creator.go
> +	err := cm.fetchCommonData()
Should we pass a context as well? instead of generating a new one in `common_data.go`.

2022-04-27 18:46 UTC, uri-weisman commented on transformer/common_data.go
> +	client, err := kubernetes.GetKubernetesClient("", kubernetes.KubeClientOptions{})
IMHO, might be better to reuse the k8s client.

2022-04-28 10:07 UTC, eyalkraft requested changes
please ignore the comments that I added on the old version of the code

2022-04-28 10:07 UTC, eyalkraft commented on transformer/common_data.go
> +		logp.Error(fmt.Errorf("fetchCommonData error in GetKubernetesClient: %w", err))
fyi our logging is a mess 😢 
https://github.com/elastic/security-team/issues/3020#issuecomment-1112003868

2022-04-28 10:07 UTC, eyalkraft commented on transformer/common_data.go
> +	n, err := c.kubeClient.CoreV1().Namespaces().Get(c.context, "kube-system", metav1.GetOptions{})
"kube-system" should be a constant

2022-04-28 10:07 UTC, eyalkraft commented on transformer/events_creator.go
> +	cm 			  CommonData
also weird indentation

2022-04-28 16:50 UTC, jeniawhite commented on transformer/common_data.go
> +func NewCommonData(ctx context.Context) CommonData {
@eyalkraft 
I agree with the single k8s client (unless there is an actual reason to use multiple due to concurrency or connection pool limitations).
Do you think that we should tackle the k8s client design change for fetchers/factories in this PR as part of this topic?
In the meanwhile, I've refactored and created a client that re-uses the cloudbeat's provided kubeconfig.

2022-05-01 12:38 UTC, eyalkraft requested changes
Nice! last mile

2022-05-01 12:38 UTC, eyalkraft commented on transformer/common_data_provider.go
> +	KubeClient, err := providers.KubernetesProvider{}.GetClient(cfg.KubeConfig, kubernetes.KubeClientOptions{})
out of scope but probably we'll have to do it in the future (also in the `kube_fetcher/factory`) -
get also the `KubeClientOptions` from the config (or the whole client from outside).

2022-05-01 12:38 UTC, eyalkraft commented on transformer/events_creator.go
> +	commonData 		   CommonDataInterface
indentation?

2022-05-01 12:38 UTC, eyalkraft commented on transformer/common_data_provider.go
> +// TODO: Support environments besides K8S
```suggestion
// Note: As of today Kubernetes is the only environment supported by CommonDataProvider
```

2022-05-01 12:38 UTC, eyalkraft commented on transformer/events_creator.go
> +func NewTransformer(ctx context.Context, eval evaluator.Evaluator, cdProvider CommonDataProvider, index string) (Transformer, error) {
Sorry for changing my mind, but now seeing that:
1. the cdp is only used once
2. this changes `NewTransformer` which is sort of a constructor to a possibly failing function

maybe we pass the common data directly? and use the provider in `beater/cloudbeat.go > New`

2022-05-01 12:38 UTC, eyalkraft commented on transformer/events_creator_test.go
> +
what about checking the relevant field in the for loop of this test?
or in a separate test?

2022-05-01 13:52 UTC, eyalkraft approved these changes

2022-05-01 13:56 UTC, uri-weisman approved these changes

2022-05-01 13:56 UTC, merged