Mockery
elastic/cloudbeat pull request #680
Opened 2023-01-27 14:50 UTC by olegsu

### Summary of your changes

### Screenshot/Data

### Related Issues

### Checklist
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

2023-01-29 07:01 UTC, amirbenun approved these changes
Nice!

2023-01-31 21:51 UTC, oren-zohar requested changes

2023-01-31 21:51 UTC, oren-zohar commented on justfile
> +generate-mocks:
Nice! can you please document this? would be nice to mention this [here](https://github.com/elastic/cloudbeat/blob/main/dev-docs/Development.md#mocking)

2023-01-31 21:51 UTC, oren-zohar commented on scripts/make/validate-mocks.sh
> +exit 1
I wonder if running the just command and then adding the `run: git diff --exit-code` step in the workflow will achieve the same. I want to avoid adding bash scripts to our workflows - for now, I don't see any security concern in that specific workflow since we don't use secrets, it's possible it will happen in the future and this will be an easy exploit. let's talk about this offline

2023-02-01 15:38 UTC, oren-zohar approved these changes

2023-02-02 08:15 UTC, merged