CloudFormation unique resources names
elastic/cloudbeat pull request #844
Opened 2023-04-03 15:14 UTC by amirbenun

### Summary of your changes
The CloudFormation template accepts a unique Id for creating resources whose name should be unique in the account.

### Related Issues
Resolves: https://github.com/elastic/cloudbeat/issues/840

### Checklist
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

2023-04-04 08:57 UTC, eyalkraft requested changes

2023-04-04 13:33 UTC, amirbenun commented on deploy/cloudformation/elastic-agent-ec2.yml
> +      GroupName: !Sub elastic-agent-security-group-${UniqueId}
You are right, this implementation allows multiple stacks on the same region.
Let's keep the [discussion](https://github.com/elastic/cloudbeat/issues/840) going, I also added a suggestion for how we can prevent the creation of two stacks in the same region. Once we will have a decision I will update the PR.

2023-04-11 07:13 UTC, olegsu approved these changes

2023-04-11 10:27 UTC, eyalkraft approved these changes

2023-04-11 10:48 UTC, merged