aws functional tests documentation
elastic/cloudbeat pull request #891
Opened 2023-04-24 07:38 UTC by gurevichdmitry

### Summary of your changes

Updating testing docs - adding guidelines how to develop AWS CIS functional tests.

2023-04-30 13:05 UTC, oren-zohar requested changes

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +##### Adding new CSPM test
```suggestion
#### Adding new CSPM test
```

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +#### CSPM Functional Tests
```suggestion
### CSPM Functional Tests
```

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +cis_aws_log_3_1_pass = EksAwsServiceCase(
```suggestion
```python
cis_aws_log_3_1_pass = EksAwsServiceCase(
```

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +- Update test cases dictionary or create new if not exist, for example
```suggestion
- Update the test cases dictionary or create a new one if it didn't exist, for example:
```

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +```
```suggestion
```python
```

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +```
```suggestion
```python
```

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +- If just adding new test case to exist test suite no additional steps required, the case will be added automatically
```suggestion
- If just adding a new test case to existing test suite, no additional steps are required, the case will be added automatically
```

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +- For new test suite create a test file in `./product/tests` folder, like `test_aws_logging_rules.py`
we can link here too

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +```
```suggestion
```python
```

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +```
```suggestion
```python
```

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +```
```suggestion
```python
```

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +- Update markers section in pyproject.toml with newly created marker
```suggestion
- Update markers section in `pyproject.toml` with newly created marker
```

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +- Execute test suite by running the following command and replacing marker `aws_logging_rules` by newly defined marker
```suggestion
- Execute the test suite by running the following command and replacing marker `aws_logging_rules` with newly defined marker
```

2023-04-30 13:05 UTC, oren-zohar commented on tests/README.md
> +```
```suggestion
```shell
```

2023-04-30 13:29 UTC, gurevichdmitry commented on tests/README.md
> +Tests folder location: `<project_root>/tests/product/tests`
provided relative link

2023-04-30 13:31 UTC, gurevichdmitry commented on tests/README.md
> +In order to separate and simply test development process, parametrization decorator is used.
I rephrased the sentence

2023-04-30 13:31 UTC, gurevichdmitry commented on tests/README.md
> +Tests data location: `<project_root>/tests/product/tests/data/aws`
relative link is added.

2023-05-02 07:44 UTC, oren-zohar approved these changes

2023-05-02 09:28 UTC, merged