Buildkite migration
elastic/cloudbeat pull request #944
Opened 2023-05-07 12:39 UTC by uri-weisman

### Summary of your changes

### Screenshot/Data

### Related Issues

### Checklist
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

2023-05-18 11:20 UTC, oren-zohar requested changes
Can you please make sure you remove any Jenkins reference from wherever possible? e.g.:
- .github/CODEOWNERS
- .editorconfig

2023-05-22 08:55 UTC, oren-zohar commented
@uri-weisman can you please update our [release docs](https://github.com/elastic/security-team/tree/main/docs/cloud-security-posture-team/release) (Jenkins -> Buildkite)

2023-05-22 09:08 UTC, oren-zohar commented
The scripts `./ci/scripts` should be the scripts in our CI pipelines:
- `integration-tests.sh` can be removed, we don't use it
- `validate-mocks.sh` and `connect_kind.sh` are not used by our CI, we can move them into `/scripts`

2023-05-22 09:26 UTC, uri-weisman commented on bin/hermit.hcl
> +  "CLOUDBEAT_VERSION": "8.9.0",
- https://github.com/elastic/security-team/pull/6699

2023-05-23 08:26 UTC, oren-zohar approved these changes
:rocket: :rocket: :rocket:

2023-05-23 08:26 UTC, oren-zohar commented on .buildkite/README.md
> +- **dependencies-CLOUDBEAT_VERSION-WORKFLOW.csv**: This CSV file contains a list of dependencies for the specific version of Cloudbeat being built. It helps track the dependencies used in the build p
```suggestion
- **dependencies-CLOUDBEAT_VERSION-WORKFLOW.csv**: This CSV file contains a list of dependencies for the specific Cloudbeat version being built. It helps track build dependencies.
```

2023-05-23 08:55 UTC, merged